lib/miniCrm_web/router.ex
defmodule MiniCrmWeb.Router do
  use MiniCrmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MiniCrmWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/accounts", AccountController do
      resources "/notes", NoteController, only: [:create]
    end
    resources "/opportunities", OpportunityController
    resources "/leads", LeadController
    resources "/contacts", ContactController do
      post "/notes", NoteController, :create_contact
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MiniCrmWeb do
  #   pipe_through :api
  # end
end

lib/miniCrm_web/views/layout_view.ex
defmodule MiniCrmWeb.LayoutView do
  use MiniCrmWeb, :view
end

lib/miniCrm_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MiniCrm · Phoenix Framework</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header class="navbar">
      <section class="navbar-section">
        <h2 class="">CRM</h2>
        <%= link "Accounts", to: Routes.page_path(@conn, :index), class: "btn btn-link link" %>
        <%= link "Opportunities", to: Routes.opportunity_path(@conn, :index), class: "btn btn-link link" %>
        <%= link "Leads", to: Routes.lead_path(@conn, :index), class: "btn btn-link link" %>
        <%= link "Contacts", to: Routes.contact_path(@conn, :index), class: "btn btn-link link" %>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>