lib/miniCrm_web/router.ex
defmodule MiniCrmWeb.Router do
  use MiniCrmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MiniCrmWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/accounts", AccountController do
      resources "/notes", NoteController, only: [:create]
    end
    resources "/opportunities", OpportunityController
    resources "/leads", LeadController
    resources "/contacts", ContactController do
      post "/notes", NoteController, :create_contact
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MiniCrmWeb do
  #   pipe_through :api
  # end
end

lib/miniCrm/crm/contact.ex
defmodule MiniCrm.CRM.Contact do
  use Ecto.Schema
  import Ecto.Changeset

  alias MiniCrm.CRM.Account
  alias MiniCrm.CRM.Note

  schema "contacts" do
    field :city, :string
    field :country, :string
    field :department, :string
    field :email, :string
    field :name, :string
    field :phone, :string
    field :street, :string
    field :title, :string
    belongs_to :account, Account
    has_many :notes, Note

    timestamps()
  end

  @doc false
  def changeset(contact, attrs) do
    contact
    |> cast(attrs, [:name, :email, :phone, :title, :department, :street, :city, :country])
    |> validate_required([:name, :email, :phone, :title, :department, :street, :city, :country])
  end
end

lib/miniCrm_web/controllers/contact_controller.ex
defmodule MiniCrmWeb.ContactController do
  use MiniCrmWeb, :controller

  alias MiniCrm.CRM
  alias MiniCrm.CRM.{Contact, Note}

  def index(conn, _params) do
    contacts = CRM.list_contacts()
    render(conn, "index.html", contacts: contacts)
  end

  def new(conn, _params) do
    changeset = CRM.change_contact(%Contact{})
    accounts = CRM.list_repo_accounts()
    countries = CRM.get_countries()
    title = ["Mr", "Mrs", "Miss", "Dr.", "Prof."]
    render(conn, "new.html", changeset: changeset, accounts: accounts, countries: countries, title: title)
  end

  def create(conn, %{"contact" => contact_params}) do
    id = Map.get(contact_params, "account_id")
    account = CRM.get_account!(id)
    case CRM.create_contact(account, contact_params) do
      {:ok, contact} ->
        conn
        |> put_flash(:info, "Contact created successfully.")
        |> redirect(to: Routes.contact_path(conn, :show, contact))

      {:error, %Ecto.Changeset{} = changeset} ->
        accounts = CRM.list_repo_accounts()
        countries = CRM.get_countries()
        title = ["Mr", "Mrs", "Miss", "Dr.", "Prof."]
        render(conn, "new.html", changeset: changeset, accounts: accounts, countries: countries, title: title)
    end
  end

  def show(conn, %{"id" => id}) do
    contact = CRM.get_contact!(id)
    note_changeset = CRM.change_note(%Note{})
    render(conn, "show.html", contact: contact, note_changeset: note_changeset)
  end

  def edit(conn, %{"id" => id}) do
    contact = CRM.get_contact!(id)
    changeset = CRM.change_contact(contact)
    render(conn, "edit.html", contact: contact, changeset: changeset)
  end

  def update(conn, %{"id" => id, "contact" => contact_params}) do
    contact = CRM.get_contact!(id)

    case CRM.update_contact(contact, contact_params) do
      {:ok, contact} ->
        conn
        |> put_flash(:info, "Contact updated successfully.")
        |> redirect(to: Routes.contact_path(conn, :show, contact))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", contact: contact, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    contact = CRM.get_contact!(id)
    {:ok, _contact} = CRM.delete_contact(contact)

    conn
    |> put_flash(:info, "Contact deleted successfully.")
    |> redirect(to: Routes.contact_path(conn, :index))
  end
end

lib/miniCrm_web/views/contact_view.ex
defmodule MiniCrmWeb.ContactView do
  use MiniCrmWeb, :view
end

lib/miniCrm_web/templates/contact/edit.html.eex
<h1>Edit Contact</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.contact_path(@conn, :update, @contact)) %>

<span><%= link "Back", to: Routes.contact_path(@conn, :index) %></span>

lib/miniCrm_web/templates/contact/form.html.eex
<div class="form c2">
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
  <%= label f, :name, class: "form-label" %>
  <%= text_input f, :name, class: "form-input" %>
  <%= error_tag f, :name %>
  </div>

<div class="columns">
    <div class="column col-6">
    <div class="form-group">
  <%= label f, :email, class: "form-label" %>
  <%= text_input f, :email, class: "form-input" %>
  <%= error_tag f, :email %>
</div>
  </div>
  <div class="column col-6">
    <div class="form-group">
  <%= label f, :phone, class: "form-label" %>
  <%= text_input f, :phone, class: "form-input" %>
  <%= error_tag f, :phone %>
</div>
  </div>
  </div>

<div class="form-group">
  <%= label f, :account_id, class: "form-label" %>
  <%= select f, :account_id, @accounts, class: "form-input" %>
  <%= error_tag f, :account_id %>
  </div>

<div class="columns">
    <div class="column col-6">
    <div class="form-group">
  <%= label f, :title, class: "form-label" %>
  <%= select f, :title, @title, class: "form-select" %>
  <%= error_tag f, :title %>
  </div>
</div>

<div class="column col-6">
    <div class="form-group">
  <%= label f, :department, class: "form-label" %>
  <%= text_input f, :department, class: "form-input" %>
  <%= error_tag f, :department %>
</div>
</div>
</div>

<div class="form-group">
  <%= label f, :street, class: "form-label" %>
  <%= textarea f, :street, class: "form-input" %>
  <%= error_tag f, :street %>
</div>

<div class="columns">
    <div class="column col-6">
    <div class="form-group">
  <%= label f, :city, class: "form-label" %>
  <%= text_input f, :city, class: "form-input" %>
  <%= error_tag f, :city %>
  </div>
</div>

<div class="column col-6">
    <div class="form-group">
  <%= label f, :country, class: "form-label" %>
  <%= select f, :country, @countries, class: "form-select" %>
  <%= error_tag f, :country %>
</div>
</div>
</div><br>

  <div class="float-right">
        <%= link "Cancel", to: Routes.contact_path(@conn, :index), class: "btn" %>
        <%= submit "Create Contact", class: "btn btn-success" %>
      </div>
<% end %>
</div>
  </div>

lib/miniCrm_web/templates/contact/index.html.eex
<div class="content">
  <div class="columns">
    <div class="column">
      <span class="float-right"><%= link "Create Contact", to: Routes.contact_path(@conn, :new), class: "acc_btn" %></span>
    </div>
    <div class="column col-12 col-mx-auto">
      <table class="table c2">
        <thead>
          <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Account</th>
          </tr>
        </thead>
        <tbody>
      <%= for contact <- @contacts do %>
          <tr>
            <td><%= link contact.name, to: Routes.contact_path(@conn, :show, contact) %></td>
            <td><%= contact.email %></td>
            <td><%= contact.phone %></td>
            <td><%= contact.account.name %></td>
          </tr>
      <% end %>
        </tbody>
    </table>

lib/miniCrm_web/templates/contact/new.html.eex
<div class="content">
  <div class="columns">
    <div class="column col-12">
      <span class="float-left"><button class="btn btn-sm"><strong><</strong> Back</button></span>
    </div>
    <div class="column col-6">
     <%= render "form.html", Map.put(assigns, :action, Routes.contact_path(@conn, :create)) %>
    </div>
</div>  
</div> 

lib/miniCrm_web/templates/contact/show.html.eex
<div class="content">
  <div class="columns">
    <div class="column col-12">
      <span class="float-left"><button class="btn btn-sm"><strong><</strong> Back</button></span>
    </div>
    <div class="column col-4">
      <div class="show c2">
        <div class="sum_d">
          <h5>Contact Details</h5>
          <hr>
          <h4><%= @contact.name %></h4>
          <p><span class="lead_txt"><i class="fa fa-envelope"></i> <%= @contact.email %></span></p>
          <p><span class="lead_txt"><i class="fa fa-phone"></i> <%= @contact.phone %></span></p>
          <p><span class="lead_txt"><i class="fa fa-user"></i> <%= @contact.department %></span></p>
          <p><span class="lead_txt"><i class="fa fa-address-book"></i> <%= @contact.street %></span></p>
        </div>
      </div>

      <div class="columns">
    <div class="column col-12">
      <div class="show c2">
        <div class="sum_d">
          <h5>Account</h5>
          <hr>
          <p><%= link @contact.account.name, to: Routes.account_path(@conn, :show, @contact.account.name) %></p>
        </div>
      </div>
    </div>
  </div>
    </div>

    <div class="column col-4">
        <div class="panel show c2">
          <div class="panel-header">
            <div class="panel-title h4">Notes</div>
            <hr>
          </div>
          <div class="panel-body">
            <%= for note <- @contact.notes do %>
              <div class="tile">
                <div class="tile-content">
                    <div class="toast toast-success">
                      <span class="tile-title text-bold"><%= note.inserted_at %></span>
                      <p class="tile-subtitle"><%= note.body %></p>
                    </div>
                </div>
              </div><br>
            <% end %>
          </div>
          <div class="panel-footer">
            <%= form_for @note_changeset, Routes.contact_note_path(@conn, :create_contact, @contact), fn f -> %>
              <div class="input-group">
                <input id="note_body" name="note[body]" class="form-input" type="text" placeholder="Add a note">
                <button type="submit" class="btn btn-primary input-group-btn">Send</button>
              </div>
            <% end %>
          </div>
        </div>
        
  </div>
  